
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend/*

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Installing Go"
    sudo apt update
    sudo apt install golang-go -y
    go version
  displayName: 'Install Go'

- checkout: self

- script: |
    echo "Downloading dependencies"
    cd backend
    go mod download
  displayName: 'Download Dependencies'

- script: |
    echo "Building Go application"
    cd backend
    go build -o app
  displayName: 'Build Go Application'

- script: |
    echo "Running tests"
    cd backend
    go test ./...
  displayName: 'Run Tests'

- script: ls -R
  workingDirectory: 'backend'
